name: GitAction Deploy Mule

on:
  push:
    branches:
      - 'master'

jobs:

  createJar:
    name: Create Mule Application Jar
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B -U -e -V clean -DskipTests package
      - name: Maven Deploy
        run: mvn -X -U -V -e -B -DskipTests deploy -DmuleDeploy -Dmule.version="4.3.0" -Danypoint.username="vk-absolute-medical" -Danypoint.password="Rahul@123!2412" -Dcloudhub.app="absm-dev-1" -Dcloudhub.environment="Development" -Dcloudhub.bg="Absolute-Engineering" -Dcloudhub.worker="Micro"
